# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title calculate_sum
#' @name calculate_sum
#' @rdname calculate_sum
#' @param data IntegerVector, containing numbers to add
#' @param processors Integer, number of cores to use. Default = all available
#' @description Calculate the sum of integers
#' @return Integer, containing sum of data
calculateSum <- function(data, processors) {
    .Call(`_ThreadingExample_calculateSum`, data, processors)
}

